# BugBug: Adjust these settings after the refactor

[tool.black]
line-length = 100

[tool.blackandbrown.AlignAssignments]
alignment_columns = [45,57,77]

# AlignAssignmentPlugin.Plugin.ModuleLevel | AlignAssignmentPlugin.Plugin.ClassLevel | AlignAssignmentPlugin.Plugin.InitLevel
#                      1                   |                      2                  |                      4
flags = 7

[tool.blackandbrown.AlignTrailingComments]
alignment_columns = [45,57,77]
